version: '3.8'

services:
  crap-stock-monitor:
    image: klausjones/crap-stock-monitoring:latest 
    container_name: crap-stock-monitor
    restart: unless-stopped
    volumes:
      - /dockers/crap-stock-monitoring/email_details.py:/app/email_details.py
      - /dockers/crap-stock-monitoring/data:/app/data
    environment:
      - TZ=Australia/Sydney
    command: ["--interval", "120", "--window", "07:30-10:00"]
